# Generated by Django 5.1.7 on 2025-04-23 17:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ano_mes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cargo', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_categoria', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consignataria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consignataria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isn_consignado', models.IntegerField(blank=True, null=True)),
                ('num_contrato', models.CharField(blank=True, null=True)),
                ('qtd_parcelas', models.IntegerField(blank=True, null=True)),
                ('qtd_parcelas_pagas', models.IntegerField(blank=True, null=True)),
                ('dat_primeiro_desconto', models.DateField(blank=True, null=True)),
                ('vlr_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dat_operacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(blank=True, null=True)),
                ('flg_desconto_folha', models.BooleanField(blank=True, null=True)),
                ('mes_desconto', models.IntegerField(blank=True, null=True)),
                ('ano_desconto', models.IntegerField(blank=True, null=True)),
                ('vlr_pago_folha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vlr_custo_operacao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vencimentos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'contrato_lancamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrauInstrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grauinstrucao', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grau_instrucao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Margem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comprometido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margem_liquida', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'margem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_orgao', models.CharField(blank=True, max_length=4, null=True)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'orgao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_hash', models.CharField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, null=True)),
                ('sexo', models.SmallIntegerField(blank=True, null=True)),
                ('empresa_id', models.SmallIntegerField(blank=True, null=True)),
                ('prontuario', models.CharField(blank=True, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('grau_instrucao_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_id', models.IntegerField(blank=True, null=True)),
                ('vencimento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'pessoa_vencimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'situacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusConsignado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_consignado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusContrato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_vinculo', models.CharField(blank=True, max_length=31, null=True)),
            ],
            options={
                'db_table': 'tipo_vinculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelAuditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('audit_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'model_audit_settings',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('is_temporary_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
