# Generated by Django 5.1.7 on 2025-06-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnoMes',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Consignataria',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='ContratoLancamento',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='GrauInstrucao',
        ),
        migrations.DeleteModel(
            name='Margem',
        ),
        migrations.DeleteModel(
            name='Orgao',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaVencimento',
        ),
        migrations.DeleteModel(
            name='Situacao',
        ),
        migrations.DeleteModel(
            name='StatusConsignado',
        ),
        migrations.DeleteModel(
            name='StatusContrato',
        ),
        migrations.DeleteModel(
            name='TipoVinculo',
        ),
    ]
